kumuluzee:
  name: ratings
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  config:
    etcd:
      hosts: http://etcd:2379
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                    <Configuration name="ratings">
                      <Appenders>
                        <Console name="console" target="SYSTEM_OUT">
                          <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                        </Console>
                        <Socket name="logstash" host="ff4d4ecb-1989-4f63-8cd6-0e643ceacce8-ls.logit.io" port="11748"
                         protocol="tcp">
                          <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                        </Socket>
                      </Appenders>
                      <Loggers>
                        <Root level="all">
                          <AppenderRef ref="console" level="info"/>
                          <AppenderRef ref="logstash" level="trace"/>
                        </Root>
                      </Loggers>
                    </Configuration>'
configuration-properties:
  db-url: jdbc:mysql://10.87.192.3:3306/ratings
  db-user: root
  db-password: 8MC17rIF68NyyoBC